import type {Metadata} from "next";

import {Inter} from "next/font/google";
import React from "react";
import "../styles/globals.css";

import {NextProvider} from "./next-ui-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
