import type {Metadata} from "next";

// eslint-disable-next-line import/order
import {Inter} from "next/font/google";

import "../styles/globals.css";
import React from "react";

import {Providers} from "./providers";
import TopLoader from "./top-loader";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>
            <TopLoader />
            {children}
          </Providers>
      </body>
    </html>
  );
}
